@echo off
echo Kopiere alle Dateien zum Desktop...
xcopy /E /Y /I "C:\Users\nazan\OneDrive\Dokumente\nanil369\nanil-pulse\_Backup_Final_Files\wedding-project\*" "C:\Users\nazan\Desktop\wedding-project\" >nul 2>&1
echo Fertig! Öffne Browser...
start "" "C:\Users\nazan\Desktop\wedding-project\index.html"
